import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Image, TouchableOpacity, Share } from 'react-native';
import { COLORS, SPACING } from '../constants/theme';
import { MOCK_REPORT } from '../services/mockData';
import { Ionicons } from '@expo/vector-icons';
import Button from '../components/Button';

export default function ReportScreen({ navigation, route }) {
    const data = route.params?.reportData || MOCK_REPORT; // In real app, fetch by ID

    const handleExport = async () => {
        try {
            await Share.share({
                message: `Check out this innovation report for ${data.summary.title} generated by Auto-Invent!`,
            });
        } catch (error) {
            // error
        }
    };

    return (
        <ScrollView style={styles.container}>
            {/* Hero / Summary */}
            <View style={styles.section}>
                <Text style={styles.reportTitle}>{data.summary.title.toUpperCase()}</Text>
                <View style={styles.summaryBox}>
                    {data.summary.highlights.map((h, i) => (
                        <View key={i} style={styles.highlightRow}>
                            <Ionicons name="flash" size={14} color={COLORS.accent} />
                            <Text style={styles.highlightText}>{h}</Text>
                        </View>
                    ))}
                </View>
            </View>

            {/* 1. FUNCTIONS */}
            <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>1. FUNCTION ANALYSIS</Text></View>
            <View style={styles.section}>
                {data.functions.map((f, i) => (
                    <View key={i} style={styles.row}>
                        <Text style={styles.rowTitle}>{f.name}</Text>
                        <Text style={[styles.tag, f.type === 'Primary' ? styles.tagPrimary : styles.tagSec]}>{f.type}</Text>
                    </View>
                ))}
            </View>

            {/* 2. FAILURE MODES */}
            <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>2. FAILURE MODES</Text></View>
            <View style={styles.section}>
                {data.failures.map((f, i) => (
                    <View key={i} style={styles.card}>
                        <View style={styles.row}>
                            <Text style={styles.cardTitle}>{f.part}</Text>
                            <RiskBadge level={f.risk} />
                        </View>
                        <Text style={styles.cardBody}>{f.note}</Text>
                    </View>
                ))}
            </View>

            {/* 3. IMPROVEMENTS */}
            <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>3. IMPROVEMENTS & COST</Text></View>
            <View style={styles.section}>
                {data.improvements.map((imp, i) => (
                    <View key={i} style={styles.card}>
                        <Text style={styles.cardTitle}>{imp.title}</Text>
                        <View style={styles.metaGrid}>
                            <MetaTag label="IMPACT" value={imp.impact} color={COLORS.primary} />
                            <MetaTag label="COST" value={imp.cost === '+' ? 'INC' : imp.cost === '-' ? 'DEC' : 'SAME'} />
                            <MetaTag label="DIFF" value={imp.difficulty} />
                        </View>
                    </View>
                ))}
            </View>

            {/* 4. CONCEPTS (IMAGES) */}
            <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>4. VISUAL CONCEPTS</Text></View>
            <ScrollView horizontal contentContainerStyle={{ paddingHorizontal: SPACING.l, paddingBottom: SPACING.xl }}>
                {data.concepts.map((c, i) => (
                    <View key={i} style={styles.conceptCard}>
                        <Image source={{ uri: c.image }} style={styles.conceptImage} />
                        <View style={styles.conceptInfo}>
                            <Text style={styles.conceptTitle}>{c.name}</Text>
                            <Text style={styles.conceptDesc}>{c.desc}</Text>
                        </View>
                    </View>
                ))}
            </ScrollView>

            {/* Footer Actions */}
            <View style={{ padding: SPACING.l, paddingBottom: 50 }}>
                <Button title="EXPORT PDF REPORT" onPress={handleExport} />
                <View style={{ height: 10 }} />
                <Button title="EDIT PROJECT" variant="outline" onPress={() => { }} />
            </View>

        </ScrollView>
    );
}

const RiskBadge = ({ level }) => {
    const color = level === 'High' ? COLORS.status.error : level === 'Medium' ? COLORS.status.warning : COLORS.status.success;
    return (
        <View style={[styles.riskBadge, { backgroundColor: color }]}>
            <Text style={styles.riskText}>{level.toUpperCase()}</Text>
        </View>
    );
};

const MetaTag = ({ label, value, color }) => (
    <View style={{ flexDirection: 'row', alignItems: 'center' }}>
        <Text style={{ color: COLORS.text.secondary, fontSize: 10, marginRight: 4 }}>{label}:</Text>
        <Text style={{ color: color || 'white', fontSize: 10, fontWeight: 'bold' }}>{value.toUpperCase()}</Text>
    </View>
);

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.background },
    sectionHeader: { paddingHorizontal: SPACING.l, paddingVertical: SPACING.s, backgroundColor: COLORS.surfaceHighlight },
    sectionTitle: { color: COLORS.text.secondary, fontSize: 12, fontWeight: '700', letterSpacing: 1 },
    section: { padding: SPACING.l },
    reportTitle: { color: 'white', fontSize: 24, fontWeight: '800', marginBottom: SPACING.m },
    summaryBox: { backgroundColor: COLORS.surface, padding: SPACING.m, borderRadius: 8, borderWidth: 1, borderColor: COLORS.border },
    highlightRow: { flexDirection: 'row', marginBottom: 8, gap: 8 },
    highlightText: { color: COLORS.text.primary, fontSize: 14, flex: 1 },

    row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    rowTitle: { color: 'white', fontSize: 16 },
    tag: { fontSize: 12, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, overflow: 'hidden' },
    tagPrimary: { backgroundColor: COLORS.primary, color: 'white' },
    tagSec: { backgroundColor: COLORS.surfaceHighlight, color: COLORS.text.secondary },

    card: { backgroundColor: COLORS.surface, padding: SPACING.m, borderRadius: 8, marginBottom: SPACING.m, borderWidth: 1, borderColor: COLORS.border },
    cardTitle: { color: 'white', fontWeight: '700', fontSize: 16, marginBottom: 4 },
    cardBody: { color: COLORS.text.secondary, fontSize: 14 },
    riskBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
    riskText: { color: 'white', fontSize: 10, fontWeight: 'bold' },
    metaGrid: { flexDirection: 'row', gap: 16, marginTop: 8 },

    conceptCard: { width: 280, marginRight: SPACING.m, backgroundColor: COLORS.surface, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: COLORS.border },
    conceptImage: { width: '100%', height: 160 },
    conceptInfo: { padding: SPACING.m },
    conceptTitle: { color: 'white', fontWeight: 'bold', fontSize: 18, marginBottom: 4 },
    conceptDesc: { color: COLORS.text.secondary, fontSize: 12 }
});
